
export interface ResourceResponse {
    empId?: number;                  // Optional - generated by backend
    name: string;                    // Full name
    designation: string;            // Role/Title
    reportingTo: string;            // Manager/Supervisor
    isBillable: string;            // Billable status
    skills: string[];               // List of skills/technologies
    projectAllocation: string;      // Current assigned project
    location: string;               // Work location
    email: string;                  // Official email
    dateOfJoining: Date;          // Date in ISO format (e.g. '2024-01-01')
    remarks: string;
}