
export interface CreateResourceRequest {
    resourceID?: number;                  // Optional - generated by backend
    fullName: string;                    // Full name
    designationName: string;            // Role/Title
    managerName: string;            // Manager/Supervisor
    billable: boolean;            // Billable status
    skills: string[];               // List of skills/technologies
    projects: string;      // Current assigned project
    locationName: string;               // Work location
    email: string;                  // Official email
    doj: string;          // Date in ISO format (e.g. '2024-01-01')
    remarks: string;
};

export interface UpdateResourceRequest extends CreateResourceRequest {
    resourceID: number;
};
